### 批量创建兑换码

POST {{host}}/api/promotion/create/batch
Accept: application/json
Content-Type: application/json

{
	"count": 500,
	"type": "FREQUENCY",
	"name": "￥8.99(次数体验版)",
	"useRule": {
		"processor": "frequencyUseProcessor"
	},
	"source": "manual",
	"scene": "DEFAULT",
	"summary": "￥8.99(次数体验版) - 100 次",
	"operator": "jerry"
}

> reponse-check.js

