app-config:
  proxy:
    enable: true
    host: 127.0.0.1
    port: 1087
  apiKeys: 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
  apiHost: https://api.openai.com

logging:
  level:
    root: INFO
    com:
      opaigc: DEBUG
