server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      force: true
      charset: utf-8
      enabled: true
      uri-encoding: utf-8

flyway:
  enabled: true
  locations: classpath:db/migration
  baseline-on-migrate: true
  out-of-order: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-generated-keys: true
  mapper-locations: classpath*:mapper/**/*Mapper.xml

# 登录配置
login:
  max-fail-times: 5
  lock-time: 10 # 10 minutes
  expire-time: 30 # 30 days

  # 登录安全配置
  security:
    jwt:
      secret-key: u1shfur#10
      expire-in: 3600000 # 60 minutes duration by default: 60 minutes * 60 seconds * 1000 miliseconds

logging:
  level:
    root: info
    org.springframework: info
    org:
      springframework:
        security: debug
      flywaydb: debug

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jackson:
    # 日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      # 格式化输出
      indent_output: true
      # 忽略无法转换的对象
      fail_on_empty_beans: false
      # 日期格式化
      write-dates-as-timestamps: false
    # 设置空如何序列化
    defaultPropertyInclusion: NON_EMPTY
    deserialization:
      # 允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
    parser:
      # 允许出现特殊字符和转义符
      allow_unquoted_control_chars: true
      # 允许出现单引号
      allow_single_quotes: true
    time-zone: GMT+8
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: 6379
      database: 0
      password: ${REDIS_PASSWORD:}
      lettuce:
        pool:
          max-active: 1000
          max-wait: 1000ms
          max-idle: 100
      ssl: false
  datasource:
    url: ${MYSQL_HOST:jdbc:mysql://localhost:3306/omni_aigc?createDatabaseIfNotExist=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:123456}
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000

app-config:
  proxy:
    enable: ${PROXY_ENABLE:false}
    host: 127.0.0.1
    port: 1087
  # 多个key用,分割
  apiKeys: ${API_KEYS:your api key}
  apiHost: ${API_HOST:https://api.openai.com}
