server:
  port: 8080
  servlet:
    context-path: /

flyway:
  enabled: true
  locations: classpath:db/migration
  baseline-on-migrate: true
  out-of-order: true


# 登录配置
login:
  max-fail-times: 5
  lock-time: 10 # 10 minutes
  expire-time: 30 # 30 days

  # 登录安全配置
  security:
    jwt:
      secret-key: u1shfur#10
      expire-in: 3600000 # 60 minutes duration by default: 60 minutes * 60 seconds * 1000 miliseconds

logging:
  level:
    root: info
    org.springframework: info
    org:
      springframework:
        security: debug
      flywaydb: debug

spring:
  jackson:
    # 日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      # 格式化输出
      indent_output: true
      # 忽略无法转换的对象
      fail_on_empty_beans: false
    # 设置空如何序列化
    defaultPropertyInclusion: NON_EMPTY
    deserialization:
      # 允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
    parser:
      # 允许出现特殊字符和转义符
      allow_unquoted_control_chars: true
      # 允许出现单引号
      allow_single_quotes: true
    time-zone: GMT+8
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: 6379
      database: 0
      password: ${REDIS_PASSWORD:}
      lettuce:
        pool:
          max-active: 1000
          max-wait: 1000ms
          max-idle: 100
      ssl: false
  datasource:
    url: ${MYSQL_HOST:jdbc:mysql://localhost:3306/omni_aigc?createDatabaseIfNotExist=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:123456}
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      master:
        url: ${MYSQL_HOST:jdbc:mysql://localhost:3306/omni_aigc?createDatabaseIfNotExist=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC}
        username: ${MYSQL_USERNAME:root}
        password: ${MYSQL_PASSWORD:123456}
      slave:
        enabled: false
      minIdle: 5
      maxActive: 15
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username:
        login-password:
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

app-config:
  env: ${ENV:local}
  proxy:
    host: 127.0.0.1
    port: 1087
  # 多个key用,分割
  apiKeys: ${API_KEYS:your api key}
  apiHost: ${API_HOST:https://api.openai.com}
