version: '3'

services:
  chat:
    image: fullbearded/omniaigc:latest
    restart: always
    container_name: omniaigc
    networks:
      openaigc_network:
    expose:
      - "80"
    ports:
      - 80:80
networks:
  openaigc_network:
